name: Java with Gradle Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'oracle'
          architecture: x64

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Junit FileIO
        run: FileIOTest.java
      - name: Junit Log
        run: LogTest.java
      - name: Junit ScheduleFromLog
        run: ScheduleFromLog.java
      - name: Junit Shedule
        run: ScheduleTest.java
      - name: Junit Search
        run: SearchTest.java
      - name: Junit TimeSlot
        run: TimeSlotTest.java
