name: Java with Gradle Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'oracle'
          architecture: x64

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Junit Tests
        run: ./gradlew test
